name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Have an issue? ping buddywhitman#1784 on discord for immediate response"
        pr-message: "Thanks a million for your time and effort! I'll get back to you asap"
